# 基础信息配置
title: XiaomingX的个人博客
subtitle: "技术分享与思考"
description: >
  欢迎访问我的技术博客，这里会分享编程经验和技术见解，专注于前端开发、后端架构与云原生技术
author: XiaomingX
language: zh-CN

# 网站URL配置
baseurl: "" 
url: "https://xiaomingx.github.io"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"

# 主题设置
theme: minima

# 社交媒体配置
social:
  github: XiaomingX
  twitter: xiaomingx
  email: xiaomingx@example.com

# 构建设置
markdown: kramdown
highlighter: rouge

# 插件配置
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 文章设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 默认布局设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: XiaomingX
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - LICENSE
  - .git
  - .github
